# Generated by Django 6.0.3 on 2026-03-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0041_event_og_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlausibleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('plausible_url', models.CharField(max_length=255)),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plausible_url', to='event.event')),
            ],
        ),
    ]
